### ISSUE TITLE
Adapting the Dynamic Adaptive Online Assessment System

### ISSUE THREAD

**Issue by jdpigeon** [NeuroTechX/neurodoro#1]
First step in using the Dynamic Adaptive Online Assesment System to collect data for Neurodoro's classifier training is to modify it so it can run in our app and lay down training info alongside the EEG data that is being collected

- Modify task parameters to allow epochs of optimal performance to be identified
- Remove sign in requirement
- Use [Window.postMessage()](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to send difficulty and performance data to the app after every trial. We can use Webview's onPostMessage() function to grab this data
- QA for making sure test works well on phone screen (might need to bridge to React Native for button presses?)

**Comment by cbattista** [comment]
Modify task parameters - I should probably tackle this (at least the first tweak) so that it's clear how to mod the system.  It's one of those 'simple if you know how' things - might be wise to create a separate issue so we can have a discussion around the fine details of that.

Sign in - do we want to remove that step,  _or_ have folks create an account?  If they have their own account it makes it possible to do repeated testing on the same person.  But, quite easy to allow a guest login as well.

Window.postMessage() - there's a data logging function that gets called every trials already, so we just need to add this line in the same place and we are off to the races.

In terms of QA - I have used it successfully on tablet screens (iPads and my Samsung S3) and it handles touch just fine - the game engine it runs on top of - http://phaser.io/ - makes this pretty straightforward.  Definitely worth checking out on other devices though!

**Comment by jdpigeon** [comment]
Awesome.

I'll get started on setting stuff up further down the line until you have a chance to adapt it.

As for the sign in, I think we just want to make it as quick as possible to get to the test. If we want to keep track of data coming from the same person, we can do that in the app when we send EEG data to the database.

Good to hear about the game engine! Should be super easy to run then.
